### ISSUE TITLE
Copying from another machine

### ISSUE THREAD

**Issue by MatthewAlner** [lejacobroy/aerials-downloader#5]
I had manually downloaded all the screensavers on another machine before I found this script 🤦🏻‍♂️ would have been a life saver!

If i'm reading it right I think if I copy the `4KSDR240FPS` folder from the machine that has them all to this one and then just run the `updateSQL()` and `killService()` functions that'll have the same effect, without having to actually download them all again?

Is there a reason for setting `718364962.0204` (10/06/1992) as a timestamp for all the `ZLASTDOWNLOADED` fields or could it be any time in the past?

Many thanks

Matt

**Comment by lejacobroy** [comment]
You are right, you can call only the last two functions after having copied the files and it should work.
It even checks if the file is already downloaded, so you could leave the script as is and select 'all aerials' when asked.

I found the timestamp value in a previous reddit discussion which inspired me to create the tool, I haven't investigated much. If it works, it works ;) 

My huch is that the timestamp needs to be a certain amount of time in the past to trigger a "rescan" of the assets and update the Settings view.
