### ISSUE TITLE
how to delete wallpapers

### ISSUE THREAD

**Issue by AboodeDaBOSS** [lejacobroy/aerials-downloader#7]
I totally underestimated the 65 gigabytes warning lol I would like to delete them all and start over.
I used the commands in this https://forums.macrumors.com/threads/how-to-remove-downloaded-aerial-wallpapers.2392675/

**Comment by lejacobroy** [comment]
I always worry of copying commands from internet that you don't fully understand, they can wipe your system.
You can simply delete the files here : /Library/Application Support/com.apple.idleassetsd/Customer/4KSDR240FPS/
